name: booksapp_internship_assignment
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  connectivity_plus: ^4.0.2
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  email_validator: ^2.1.17
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.0
  get: 4.6.5
  localstorage: ^4.0.1+4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
